import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Modal from "react-modal";
import { useRouter } from "next/router";

const customStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
  },
};

export default function Home() {
  const [emails, setEmails] = useState({ owner: "", coSigner: "" });
  const [showModal, setShowModal] = useState(false);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Lawyered up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">LawyeredUp!</a>
        </h1>

        <p className={styles.description}>
          To get started with your NDA, click below to{" "}
          <code className={styles.code}>Edit</code>
        </p>

        <div className={styles.grid}>
          <a
            onClick={() => {
              setShowModal(true);
            }}
            className={styles.card}
          >
            <h2>Freelance NDA &rarr;</h2>
            <p>
              A contract by which one or more parties agree not to disclose
              confidential information that they have shared with each other as
              a necessary part of doing business together.
            </p>
          </a>

          {/* <a href="#" className={styles.card}>
            <h2>Agreement of Service &rarr;</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Contracts &rarr;</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Proof of work Agreement &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️. All rights reserved. &copy; LayweredUp
        </a>
      </footer>

      <Modal
        isOpen={showModal}
        onAfterOpen={() => {}}
        onRequestClose={() => {}}
        style={customStyles}
        contentLabel="Example Modal"
      >
        <h2>Enter emails to receive NDA</h2>
        <input
          className={styles.inputField}
          placeholder="Enter your email"
          onChange={(e) => {
            setEmails({ ...emails, owner: e.target.value });
          }}
        />
        <br />
        <br />
        <input
          className={styles.inputField}
          placeholder="Enter co-signer's email"
          onChange={(e) => {
            setEmails({ ...emails, coSigner: e.target.value });
          }}
        />
        <br />
        <br />
        <button
          className={styles.button}
          onClick={() => {
            if (!emails.owner || !emails.coSigner) {
              alert("Emails are required!");
            } else if (emails.owner === emails.coSigner) {
              alert("Emails should not be the same!");
            } else {
              router.push({
                pathname: "/sign",
                query: { ...emails },
              });
            }
          }}
        >
          Okay! Proceed
        </button>

        <br />
        <br />
        <button
          className={styles.button}
          onClick={() => {
            setShowModal(false);
          }}
        >
          Cancel
        </button>
      </Modal>
    </div>
  );
}
